import { australianBusinessData } from "@/data/australia/business";
export const categories = [
  {
    slug: "money",
    title: "Money",
    icon: "wallet",
    description: "Budgets, bills and everyday costs.",
    color: "gold",
  },
  {
    slug: "work",
    title: "Work",
    icon: "briefcase",
    description: "Pay, employment and your next move.",
    color: "blue",
  },
  {
    slug: "business",
    title: "Business & Tradies",
    icon: "hammer",
    description: "Better quotes. Healthier businesses.",
    color: "green",
  },
  {
    slug: "home",
    title: "Home",
    icon: "house",
    description: "Energy, renovations and household life.",
    color: "orange",
  },
  {
    slug: "cars-travel",
    title: "Cars & Travel",
    icon: "car",
    description: "The real cost of getting there.",
    color: "blue",
  },
  {
    slug: "caravan-camping",
    title: "Caravan & Camping",
    icon: "tent",
    description: "Plan your load and your next adventure.",
    color: "green",
  },
] as const;
export type CategorySlug = (typeof categories)[number]["slug"];
export type Tool = {
  slug: string;
  title: string;
  shortTitle: string;
  question: string;
  description: string;
  category: CategorySlug;
  icon: string;
  status: "live" | "planned";
  featured: boolean;
  keywords: string[];
  relatedTools: string[];
  lastUpdated: string;
  sources: readonly { title: string; url: string; note: string }[];
};
export const tools: Tool[] = [
  {
    slug: "trade-toolkit",
    title: "Trade Business Toolkit",
    shortTitle: "Trade toolkit",
    question: "Ready to price, quote and get paid?",
    description:
      "Check job profit, build quotes and invoices, define your scope and draft client emails.",
    category: "business",
    icon: "hammer",
    status: "live",
    featured: true,
    keywords: [
      "quote",
      "invoice",
      "scope",
      "email",
      "gst",
      "hourly",
      "markup",
      "tradie",
    ],
    relatedTools: ["job-profit-calculator"],
    lastUpdated: "2026-10-08",
    sources: australianBusinessData.sources,
  },
  {
    slug: "job-profit-calculator",
    title: "Tradie Job Profit Calculator",
    shortTitle: "Job profit",
    question: "Is this job actually profitable?",
    description:
      "See your real job cost, profit margin and what you should quote.",
    category: "business",
    icon: "hammer",
    status: "live",
    featured: true,
    keywords: ["tradie", "quote", "margin", "profit", "pricing"],
    relatedTools: ["employee-true-cost"],
    lastUpdated: australianBusinessData.checkedOn,
    sources: australianBusinessData.sources,
  },
  {
    slug: "job-comparison",
    title: "Should I Take This Job?",
    shortTitle: "Job comparison",
    question: "Is that new job really worth it?",
    description: "Compare pay, commuting costs and the time you get back.",
    category: "work",
    icon: "briefcase",
    status: "planned",
    featured: true,
    keywords: ["salary", "career", "commute"],
    relatedTools: ["fifo-comparison"],
    lastUpdated: "",
    sources: [],
  },
  {
    slug: "employee-true-cost",
    title: "Employee True Cost",
    shortTitle: "Employee cost",
    question: "What does an employee really cost?",
    description:
      "Look beyond salary to the full cost of another pair of hands.",
    category: "business",
    icon: "users",
    status: "planned",
    featured: false,
    keywords: ["super", "staff", "salary"],
    relatedTools: ["job-profit-calculator"],
    lastUpdated: "",
    sources: [],
  },
  {
    slug: "fifo-comparison",
    title: "FIFO Job Comparator",
    shortTitle: "FIFO comparison",
    question: "Which FIFO roster works for you?",
    description: "Compare income with hours worked and days away from home.",
    category: "work",
    icon: "briefcase",
    status: "planned",
    featured: false,
    keywords: ["fifo", "roster", "mining"],
    relatedTools: ["job-comparison"],
    lastUpdated: "",
    sources: [],
  },
  {
    slug: "energy-detective",
    title: "Household Energy Detective",
    shortTitle: "Energy detective",
    question: "Where is your power bill going?",
    description: "Find the biggest electricity costs hiding around your home.",
    category: "home",
    icon: "zap",
    status: "planned",
    featured: true,
    keywords: ["electricity", "power", "appliance"],
    relatedTools: ["rent-affordability"],
    lastUpdated: "",
    sources: [],
  },
  {
    slug: "rent-affordability",
    title: "Can I Afford This Rent?",
    shortTitle: "Rent affordability",
    question: "Can you comfortably afford this rent?",
    description: "Check what is left after essentials and your savings goal.",
    category: "money",
    icon: "wallet",
    status: "planned",
    featured: false,
    keywords: ["rent", "budget", "income"],
    relatedTools: ["energy-detective"],
    lastUpdated: "",
    sources: [],
  },
  {
    slug: "road-trip-cost",
    title: "Road Trip True Cost",
    shortTitle: "Road trip cost",
    question: "What will this road trip really cost?",
    description: "Add up fuel, accommodation, food and everything in between.",
    category: "cars-travel",
    icon: "car",
    status: "planned",
    featured: false,
    keywords: ["fuel", "holiday", "travel"],
    relatedTools: ["caravan-load"],
    lastUpdated: "",
    sources: [],
  },
  {
    slug: "caravan-load",
    title: "Caravan Load Planner",
    shortTitle: "Caravan load",
    question: "Can your caravan carry all that?",
    description: "Plan your packing and see how much payload remains.",
    category: "caravan-camping",
    icon: "tent",
    status: "planned",
    featured: true,
    keywords: ["payload", "weight", "towing"],
    relatedTools: ["road-trip-cost"],
    lastUpdated: "",
    sources: [],
  },
  {
    slug: "renovation-materials",
    title: "Renovation Project Calculator",
    shortTitle: "Renovation materials",
    question: "How much flooring should you buy?",
    description:
      "Work out materials, waste and costs before you hit the shops.",
    category: "home",
    icon: "ruler",
    status: "planned",
    featured: false,
    keywords: ["flooring", "packs", "renovation"],
    relatedTools: ["job-profit-calculator"],
    lastUpdated: "",
    sources: [],
  },
  {
    slug: "sole-trader-split",
    title: "Sole Trader Money Splitter",
    shortTitle: "Money splitter",
    question: "How much of that payment is yours?",
    description: "Set aside reserves for GST, tax, super and expenses.",
    category: "money",
    icon: "wallet",
    status: "planned",
    featured: false,
    keywords: ["tax", "gst", "sole trader"],
    relatedTools: ["job-profit-calculator"],
    lastUpdated: "",
    sources: [],
  },
];
export const toolPath = (tool: Tool) => `/${tool.category}/${tool.slug}`;
